version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: postgres_file_db
    environment:
      POSTGRES_DB: pos_db #pos_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5051:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_file_ui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      #      TZ: Asia/Yangon
      TZ: Asia/Rangoon
    ports:
      - "5052:5050"
    depends_on:
      - postgres
    networks:
      - spring-network

#  redis:
#    image: redis:7.2
#    container_name: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#      - ./redis.conf:/usr/local/etc/redis/redis.conf # Mount custom config
#    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
#    environment:
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      REDIS_PASSWORD: ${REDIS_PASSWORD}
#    restart: always
#    healthcheck:
#      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#    networks:
#      - spring-network


volumes:
  postgres_data:
  redis_data:

networks:
  spring-network:
    driver: bridge
